---
abstract: "An interface to Flattr's social micro-payment API"
author:
  - 'Tom Hukins <tom@eborcom.com>'
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Flattr
requires:
  JSON: 2
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  URI::QueryParam: 0
  URI::Template: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=WebService-Flattr
  repository: git://git.scrubhole.org/WebService-Flattr
version: 0.50
